"""add count column to order product relation table

Revision ID: 1d30538d5113
Revises: c3976268278a
Create Date: 2025-04-21 12:49:38.474211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d30538d5113"
down_revision: Union[str, None] = "c3976268278a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_relation",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_relation", "count")
    # ### end Alembic commands ###
