"""add unit price column to order product relation table

Revision ID: 182c6fb7beb3
Revises: 1d30538d5113
Create Date: 2025-04-21 14:27:25.496117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "182c6fb7beb3"
down_revision: Union[str, None] = "1d30538d5113"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_relation",
        sa.Column("unit_price", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_relation", "unit_price")
    # ### end Alembic commands ###
